### ISSUE TITLE
Auto shutdown problem - Shutting down ExecutorService 'applicationTaskExecutor'

### ISSUE THREAD

**Issue by SOVANTHOEUN** [ZHENFENG13/My-BBS#2]
After I configure everything done and running success but it auto shutdown and cannot connect via localhost:8080.
Thank you. :)

<img width="1715" alt="image" src="https://user-images.githubusercontent.com/13831964/177590946-088196d0-b07f-44f8-887d-7caa453909a9.png">
<img width="1725" alt="image" src="https://user-images.githubusercontent.com/13831964/177591025-871d2ac7-62e1-491a-884c-6d31c377c749.png">

**Comment by ZHENFENG13** [comment]
你这是跑的测试用例吧，应该启动主类MyBBSApplication
